repos:
- repo: local
  hooks:
  - id: gitleaks
    name: gitleaks
    entry: gitleaks
    language: system
  - id: shellcheck
    name: shellcheck
    entry: shellcheck
    language: system
    types: [shell]
    require_serial: true
