#!/bin/sh -eu

# https://docs.voidlinux.org/xbps/repositories/mirrors/changing.html

mirror_new=mirrors.servercentral.com/voidlinux
mirror_old=repo-default.voidlinux.org

usage() {
    >&2 printf 'usage: %s [-M MIRROR]\n' "$0"
    exit 3
}

while getopts hM: opt; do
    case $opt in
        h|\?)  usage ;;
        M)  mirror_new=$OPTARG ;;
    esac
done
shift $((OPTIND-1))

set -x

sudo cp -ai /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/

for prefix in / /usr/src/void-packages ; do
    [ -d "$prefix" ] || continue
    sudo sed -i "s|$mirror_old|$mirror_new|" $prefix/etc/xbps.d/*
done

sudo xbps-install --sync
xbps-query --list-repos
