#!/bin/sh -eu

# https://docs.voidlinux.org/xbps/repositories/mirrors/changing.html

mirror=mirrors.servercentral.com/voidlinux
mirror_default=alpha.de.repo.voidlinux.org

usage() {
    printf 'usage: %s [-M MIRROR]\n' "$0"
    exit 3
}

while getopts hM: opt; do
    case $opt in
        h|\?)  usage ;;
        M)  mirror=$OPTARG ;;
    esac
done
shift $((OPTIND-1))

set -x

sudo cp -a /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/

for prefix in / /usr/src/void-packages ; do
    [ -d "$prefix" ] || continue
    sudo sed -i "s|$mirror_default|$mirror|" $prefix/etc/xbps.d/*
done

sudo xbps-install --sync
xbps-query --list-repos
