'\" t
.\"     Title: wesaugur/dotfiles
.\"    Author: Wes Augur
.\" Generator: Asciidoctor 2.0.12
.\"      Date: 2021-01-14
.\"    Manual: Wes Augur Dotfiles Manual
.\"    Source: Wes Augur Dotfiles
.\"  Language: English
.\"
.TH "DOTFILES" "7" "2021-01-14" "Wes Augur Dotfiles" "Wes Augur Dotfiles Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dotfiles \- Wes Augur Dotfiles
.SH "SYNOPSIS"
.sp
\fBdotfiles git\fP \fIGIT\-COMMAND\fP
.SH "DESCRIPTION"
.sp
dotfiles(7) is a shell alias that wraps git(1)
to simplify managing dotfiles in your home directory.
.sp
.if n .RS 4
.nf
.fam C
alias dotfiles=\(aqGIT_DIR=$HOME/.dotfiles.git GIT_WORK_TREE=$HOME\(aq
.fam
.fi
.if n .RE
.SH "INSTALLATION"
.sp
.if n .RS 4
.nf
.fam C
curl https://wesaugur.sh | sh
.fam
.fi
.if n .RE
.SH "UNINSTALLATION"
.sp
.if n .RS 4
.nf
.fam C
dotfiles git ls\-files | xargs rm
rm \-rf "$DOTFILES_GIT_DIR"
.fam
.fi
.if n .RE
.SH "EXAMPLES"
.sp
\fBdotfiles git\fP \fIstatus\fP
.RS 4
Show status of local dotfile changes
.RE
.sp
\fBdotfiles git\fP \fIdiff\fP
.RS 4
Show diff of local dotfile changes
.RE
.sp
\fBdotfiles git\fP \fIadd\fP
.RS 4
Add local dotfile changes to the git index
.RE
.sp
\fBdotfiles git\fP \fIcommit\fP
.RS 4
Record dotfile changes to the git repository
.RE
.sp
\fBdotfiles git\fP \fIpush\fP
.RS 4
Push local dotfile changes to remote git repository
.RE
.sp
\fBdotfiles git\fP \fIpull\fP
.RS 4
Pull remote dotfile changes into local git repository
.RE
.sp
\fBdotfiles\-setup\fP
.RS 4
Re\-run the setup script
.RE
.sp
\fBdotfiles\-fixup\fP
.RS 4
Fix common dotfile errors
.RE
.SH "RESOURCES"
.sp
Installer
.RS 4
.URL "https://wesaugur.sh" "" ""
.RE
.sp
Manpage
.RS 4
.URL "https://wesaugur.sh/man" "" ""
.RE
.sp
GitHub
.RS 4
\c
.URL "https://code.wes.augur.us/~" ""
.br
.URL "https://code.wes.augur.us/~/<DOTFILE>" "" ""
.RE
.SH "SEE ALSO"
.sp
git(1)
.SH "AUTHOR"
.sp
Wes Augur